### ISSUE TITLE
Add the ability to apply suppression flags for Core output

### ISSUE THREAD

**Issue by tchoutri** [tomsmeding/play-haskell#18]
On user request, it would be interesting to provide a way to apply various suppression flags (https://downloads.haskell.org/ghc/latest/docs/users_guide/debugging.html#suppressing-unwanted-information) on the Core output

**Comment by tomsmeding** [comment]
I think this is #2 already, right?

**Comment by tchoutri** [comment]
ugh, yes absolutely

**Comment by s-and-witch** [comment]
@tchoutri you can use arbitrary options using OPTIONS_GHC pragma: https://play.haskell.org/saved/IMAPoEKI
